name: MinecraftServerManager
version: ${project.version}
main: com.dalton.MinecraftServerManager
api-version: 1.13
authors: [DaltonBurchard]
description: A Minecraft server manager API
website: com.dalton.rest
